set_property  IOSTANDARD LVCMOS33 [ get_ports *]
set_property CLOCK_DEDICATED_ROUTE FALSE [ get_nets { I_qspi_clk_IBUF } ] 
set_property  PACKAGE_PIN P2 [ get_ports	{ qspi_d0 } ]
set_property  PACKAGE_PIN L14 [ get_ports	{ qspi_d1 } ] 
set_property  PACKAGE_PIN J13 [ get_ports	{ qspi_d2 } ] 
set_property  PACKAGE_PIN D13 [ get_ports	{ qspi_d3 } ] 
set_property  PACKAGE_PIN M13 [ get_ports	{ I_qspi_cs } ] 
set_property  PACKAGE_PIN H14 [ get_ports	{ I_qspi_clk } ] 
set_property  PACKAGE_PIN H4 [ get_ports	{ clk } ] 
set_property  PACKAGE_PIN D14 [ get_ports	{ rst_n } ] 
